// Code generated by go-swagger; DO NOT EDIT.

package custom_ioa

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// GetRulesMixin0Mixin45Reader is a Reader for the GetRulesMixin0Mixin45 structure.
type GetRulesMixin0Mixin45Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRulesMixin0Mixin45Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRulesMixin0Mixin45OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetRulesMixin0Mixin45Forbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetRulesMixin0Mixin45NotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetRulesMixin0Mixin45TooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRulesMixin0Mixin45OK creates a GetRulesMixin0Mixin45OK with default headers values
func NewGetRulesMixin0Mixin45OK() *GetRulesMixin0Mixin45OK {
	return &GetRulesMixin0Mixin45OK{}
}

/*
GetRulesMixin0Mixin45OK describes a response with status code 200, with default header values.

OK
*/
type GetRulesMixin0Mixin45OK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.APIRulesResponse
}

// IsSuccess returns true when this get rules mixin0 mixin45 o k response has a 2xx status code
func (o *GetRulesMixin0Mixin45OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get rules mixin0 mixin45 o k response has a 3xx status code
func (o *GetRulesMixin0Mixin45OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rules mixin0 mixin45 o k response has a 4xx status code
func (o *GetRulesMixin0Mixin45OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get rules mixin0 mixin45 o k response has a 5xx status code
func (o *GetRulesMixin0Mixin45OK) IsServerError() bool {
	return false
}

// IsCode returns true when this get rules mixin0 mixin45 o k response a status code equal to that given
func (o *GetRulesMixin0Mixin45OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get rules mixin0 mixin45 o k response
func (o *GetRulesMixin0Mixin45OK) Code() int {
	return 200
}

func (o *GetRulesMixin0Mixin45OK) Error() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45OK  %+v", 200, o.Payload)
}

func (o *GetRulesMixin0Mixin45OK) String() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45OK  %+v", 200, o.Payload)
}

func (o *GetRulesMixin0Mixin45OK) GetPayload() *models.APIRulesResponse {
	return o.Payload
}

func (o *GetRulesMixin0Mixin45OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.APIRulesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRulesMixin0Mixin45Forbidden creates a GetRulesMixin0Mixin45Forbidden with default headers values
func NewGetRulesMixin0Mixin45Forbidden() *GetRulesMixin0Mixin45Forbidden {
	return &GetRulesMixin0Mixin45Forbidden{}
}

/*
GetRulesMixin0Mixin45Forbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetRulesMixin0Mixin45Forbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get rules mixin0 mixin45 forbidden response has a 2xx status code
func (o *GetRulesMixin0Mixin45Forbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rules mixin0 mixin45 forbidden response has a 3xx status code
func (o *GetRulesMixin0Mixin45Forbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rules mixin0 mixin45 forbidden response has a 4xx status code
func (o *GetRulesMixin0Mixin45Forbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get rules mixin0 mixin45 forbidden response has a 5xx status code
func (o *GetRulesMixin0Mixin45Forbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get rules mixin0 mixin45 forbidden response a status code equal to that given
func (o *GetRulesMixin0Mixin45Forbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get rules mixin0 mixin45 forbidden response
func (o *GetRulesMixin0Mixin45Forbidden) Code() int {
	return 403
}

func (o *GetRulesMixin0Mixin45Forbidden) Error() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45Forbidden  %+v", 403, o.Payload)
}

func (o *GetRulesMixin0Mixin45Forbidden) String() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45Forbidden  %+v", 403, o.Payload)
}

func (o *GetRulesMixin0Mixin45Forbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetRulesMixin0Mixin45Forbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRulesMixin0Mixin45NotFound creates a GetRulesMixin0Mixin45NotFound with default headers values
func NewGetRulesMixin0Mixin45NotFound() *GetRulesMixin0Mixin45NotFound {
	return &GetRulesMixin0Mixin45NotFound{}
}

/*
GetRulesMixin0Mixin45NotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetRulesMixin0Mixin45NotFound struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get rules mixin0 mixin45 not found response has a 2xx status code
func (o *GetRulesMixin0Mixin45NotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rules mixin0 mixin45 not found response has a 3xx status code
func (o *GetRulesMixin0Mixin45NotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rules mixin0 mixin45 not found response has a 4xx status code
func (o *GetRulesMixin0Mixin45NotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get rules mixin0 mixin45 not found response has a 5xx status code
func (o *GetRulesMixin0Mixin45NotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get rules mixin0 mixin45 not found response a status code equal to that given
func (o *GetRulesMixin0Mixin45NotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get rules mixin0 mixin45 not found response
func (o *GetRulesMixin0Mixin45NotFound) Code() int {
	return 404
}

func (o *GetRulesMixin0Mixin45NotFound) Error() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45NotFound  %+v", 404, o.Payload)
}

func (o *GetRulesMixin0Mixin45NotFound) String() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45NotFound  %+v", 404, o.Payload)
}

func (o *GetRulesMixin0Mixin45NotFound) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetRulesMixin0Mixin45NotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRulesMixin0Mixin45TooManyRequests creates a GetRulesMixin0Mixin45TooManyRequests with default headers values
func NewGetRulesMixin0Mixin45TooManyRequests() *GetRulesMixin0Mixin45TooManyRequests {
	return &GetRulesMixin0Mixin45TooManyRequests{}
}

/*
GetRulesMixin0Mixin45TooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetRulesMixin0Mixin45TooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get rules mixin0 mixin45 too many requests response has a 2xx status code
func (o *GetRulesMixin0Mixin45TooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get rules mixin0 mixin45 too many requests response has a 3xx status code
func (o *GetRulesMixin0Mixin45TooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get rules mixin0 mixin45 too many requests response has a 4xx status code
func (o *GetRulesMixin0Mixin45TooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get rules mixin0 mixin45 too many requests response has a 5xx status code
func (o *GetRulesMixin0Mixin45TooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get rules mixin0 mixin45 too many requests response a status code equal to that given
func (o *GetRulesMixin0Mixin45TooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get rules mixin0 mixin45 too many requests response
func (o *GetRulesMixin0Mixin45TooManyRequests) Code() int {
	return 429
}

func (o *GetRulesMixin0Mixin45TooManyRequests) Error() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45TooManyRequests  %+v", 429, o.Payload)
}

func (o *GetRulesMixin0Mixin45TooManyRequests) String() string {
	return fmt.Sprintf("[GET /ioarules/entities/rules/v1][%d] getRulesMixin0Mixin45TooManyRequests  %+v", 429, o.Payload)
}

func (o *GetRulesMixin0Mixin45TooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetRulesMixin0Mixin45TooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
