// Code generated by go-swagger; DO NOT EDIT.

package discover

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryActiveDiscoveryScansParams creates a new QueryActiveDiscoveryScansParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryActiveDiscoveryScansParams() *QueryActiveDiscoveryScansParams {
	return &QueryActiveDiscoveryScansParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryActiveDiscoveryScansParamsWithTimeout creates a new QueryActiveDiscoveryScansParams object
// with the ability to set a timeout on a request.
func NewQueryActiveDiscoveryScansParamsWithTimeout(timeout time.Duration) *QueryActiveDiscoveryScansParams {
	return &QueryActiveDiscoveryScansParams{
		timeout: timeout,
	}
}

// NewQueryActiveDiscoveryScansParamsWithContext creates a new QueryActiveDiscoveryScansParams object
// with the ability to set a context for a request.
func NewQueryActiveDiscoveryScansParamsWithContext(ctx context.Context) *QueryActiveDiscoveryScansParams {
	return &QueryActiveDiscoveryScansParams{
		Context: ctx,
	}
}

// NewQueryActiveDiscoveryScansParamsWithHTTPClient creates a new QueryActiveDiscoveryScansParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryActiveDiscoveryScansParamsWithHTTPClient(client *http.Client) *QueryActiveDiscoveryScansParams {
	return &QueryActiveDiscoveryScansParams{
		HTTPClient: client,
	}
}

/*
QueryActiveDiscoveryScansParams contains all the parameters to send to the API endpoint

	for the query active discovery scans operation.

	Typically these are written to a http.Request.
*/
type QueryActiveDiscoveryScansParams struct {

	/* XCSUSERUUID.

	   User UUID
	*/
	XCSUSERUUID *string

	/* Filter.

	   Search for active discovery scans in your environment by providing an FQL filter.
	*/
	Filter *string

	/* Limit.

	   The number of active discovery scan ids to return in this response (Min: 1, Max: 100, Default: 100).
	*/
	Limit *int64

	/* Offset.

	   The index of the starting resource.
	*/
	Offset *int64

	/* Sort.

	   Sort active discovery scans by their properties. A single sort field is allowed.
	*/
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query active discovery scans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryActiveDiscoveryScansParams) WithDefaults() *QueryActiveDiscoveryScansParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query active discovery scans params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryActiveDiscoveryScansParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithTimeout(timeout time.Duration) *QueryActiveDiscoveryScansParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithContext(ctx context.Context) *QueryActiveDiscoveryScansParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithHTTPClient(client *http.Client) *QueryActiveDiscoveryScansParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXCSUSERUUID adds the xCSUSERUUID to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithXCSUSERUUID(xCSUSERUUID *string) *QueryActiveDiscoveryScansParams {
	o.SetXCSUSERUUID(xCSUSERUUID)
	return o
}

// SetXCSUSERUUID adds the xCSUSERUuid to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetXCSUSERUUID(xCSUSERUUID *string) {
	o.XCSUSERUUID = xCSUSERUUID
}

// WithFilter adds the filter to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithFilter(filter *string) *QueryActiveDiscoveryScansParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithLimit adds the limit to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithLimit(limit *int64) *QueryActiveDiscoveryScansParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithOffset(offset *int64) *QueryActiveDiscoveryScansParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSort adds the sort to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) WithSort(sort *string) *QueryActiveDiscoveryScansParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the query active discovery scans params
func (o *QueryActiveDiscoveryScansParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *QueryActiveDiscoveryScansParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XCSUSERUUID != nil {

		// header param X-CS-USERUUID
		if err := r.SetHeaderParam("X-CS-USERUUID", *o.XCSUSERUUID); err != nil {
			return err
		}
	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
